
#ALTER DATABASE testDB CHARACTER   SET utf8 COLLATE utf8_general_ci; //TODO correct table


CREATE TABLE clients
(
  id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(45) NOT NULL ,
  second_name VARCHAR(45) NOT NULL ,
  login VARCHAR(45) NOT NULL ,
  password VARCHAR(45) NOT NULL ,
  role VARCHAR(45) NOT NULL ,
  PRIMARY KEY (id)
);

# CREATE TABLE `testdb`.`clients` ( //TODO clients table as generated by MySQL (+add unique for id) (+chang places first and second names)
# `id` INT NOT NULL AUTO_INCREMENT,
# `first_name` VARCHAR(45) NOT NULL,
# `second_name` VARCHAR(45) NOT NULL,
# `login` VARCHAR(45) NOT NULL,
# `password` VARCHAR(45) NOT NULL,
# `role` VARCHAR(25) NOT NULL,
# PRIMARY KEY (`id`),
# UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
# ENGINE = InnoDB
# DEFAULT CHARACTER SET = utf8;

# CREATE TABLE `testdb`.`inspectors` ( //TODO inspectors table as generated by MySQL + add column number of reports
#                                        `id` INT NOT NULL AUTO_INCREMENT,
#                                        `second_name` VARCHAR(45) NOT NULL,
#                                        `first_name` VARCHAR(45) NOT NULL,
#                                        `login` VARCHAR(45) NOT NULL,
#                                        `password` VARCHAR(45) NOT NULL,
#                                        PRIMARY KEY (`login`),
#                                        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
#                                        UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;


# CREATE TABLE `testdb`.`declarations` (  //TODO declarations table as generated by MySQL + correction message
#                                          `id` INT NOT NULL,
#                                          `author_login` VARCHAR(45) NOT NULL,
#                                          `inspector_login` VARCHAR(45) NULL,
#                                          `declaration_year` VARCHAR(45) NOT NULL,
#                                          `tax_category` VARCHAR(45) NOT NULL,
#                                          `income` BIGINT(20) NOT NULL,
#                                          `tax_sum_declared` BIGINT(20) NOT NULL,
#                                          `status` VARCHAR(45) NOT NULL,
#                                          PRIMARY KEY (`id`),
#                                          UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
#                                          INDEX `author_login_idx` (`author_login` ASC) VISIBLE,
#                                          INDEX `inspector_login_idx` (`inspector_login` ASC) VISIBLE,
#                                          CONSTRAINT `author_login`
#                                              FOREIGN KEY (`author_login`)
#                                                  REFERENCES `testdb`.`clients` (`login`)
#                                                  ON DELETE NO ACTION
#                                                  ON UPDATE NO ACTION,
#                                          CONSTRAINT `inspector_login`
#                                              FOREIGN KEY (`inspector_login`)
#                                                  REFERENCES `testdb`.`inspectors` (`login`)
#                                                  ON DELETE NO ACTION
#                                                  ON UPDATE NO ACTION)
#     ENGINE = InnoDB
#     DEFAULT CHARACTER SET = utf8;